/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public static void main(String[] args) {
    String nome = "Aramac";
    String tipoConta = "Corrente";
    Double saldo = 1599.99;

    System.out.println("***************************************");
    System.out.println("\nNome do cliente: " + nome);
    System.out.println("\nNome do cliente: " + tipoConta);
    System.out.println("\nNome do cliente: " + saldo);
    System.out.println("***************************************");
  }

}
